name: Docker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Build Docker Compose images for ARM64
      run: |
        docker compose -f docker-compose.yml build --no-cache TARGETPLATFORM=linux/arm64

    - name: Save Docker images as tar files
      run: |
        mkdir -p docker_images
        docker compose -f docker-compose.yml config --services | while read service; do
          image_name=$(docker compose -f docker-compose.yml config | grep "image:" | grep "${service}" | awk '{print $2}')
          docker save -o docker_images/${service}.tar ${image_name}
        done

    - name: Upload Docker images to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker_images/*.tar, docker-compose.yml"
        target: "~/jbokinfo/"

    - name: Deploy Docker Compose on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/jbokinfo
          for tarfile in *.tar; do
            docker load -i $tarfile
          done
          docker compose down
          docker compose up -d